const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let risk=72,atRisk=23,tested=128,role="Payroll";
const people=[["Arun Kumar","Payroll","Clicked","High","Required"],["Priya Shah","Developer","Reported","Low","Complete"],["Rahul Menon","HR","Clicked","High","Required"],["Sneha Rao","Finance","Ignored","Low","Complete"],["Vikram Das","Developer","Reported","Low","Complete"],["Meena Iyer","Payroll","Clicked","Medium","In progress"]];
function page(id){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent=id[0].toUpperCase()+id.slice(1)}
$$(".nav").forEach(x=>x.onclick=()=>page(x.dataset.page));$$(".text").forEach(x=>x.onclick=()=>page(x.dataset.page));
function rows(){ $("#employeeRows").innerHTML=people.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td></tr>`).join("")} rows();
function activity(t,s){let d=document.createElement("div");d.innerHTML=`⚠ <b>${t}</b><small> Just now · Safe simulation</small><em>${s}</em>`;$("#activity").prepend(d)}
activity("Arun Kumar clicked Payroll simulation","Clicked");activity("Priya Shah reported Developer simulation","Reported");activity("Training completed by Finance team","Training");
$("#quickCampaign").onclick=()=>page("campaigns");
$$(".scenario").forEach(x=>x.onclick=()=>{role=x.dataset.role;$$(".scenario").forEach(y=>y.classList.remove("selected"));x.classList.add("selected");let d={Payroll:["payroll@company-demo","Salary revision notification","Your salary information has been updated.","Review notification"],Developer:["security@code-demo","New repository security alert","A new sign-in was detected on your developer account.","Review security activity"],HR:["benefits@company-demo","Benefits enrollment reminder","Your benefits enrollment window is closing soon.","Review benefits"],Finance:["accounts@company-demo","Invoice review request","A payment document is ready for review.","Review invoice"]}[role];$("#sender").textContent=d[0];$("#subject").textContent=d[1];$("#mailText").textContent=d[2];$("#simulateClick").textContent=d[3]});
$("#simulateClick").onclick=()=>{risk=Math.min(100,risk+2);atRisk++;$("#riskScore").innerHTML=risk+"<em>/100</em>";$("#riskBar").style.width=risk+"%";$("#atRisk").textContent=atRisk;activity(`${role} employee clicked simulation`,"Training");$("#modalText").textContent=`The ${role.toLowerCase()} simulation was clicked. The event was recorded locally; no external content opened.`;$("#modal").classList.add("show")};
$("#runSimulation").onclick=()=>{tested++;$("#tested").textContent=tested;activity(`${role} simulation launched`,"Campaign");toast("Safe simulation launched")};
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2500)}
$("#close").onclick=()=>$("#modal").classList.remove("show");
function train(){risk=Math.max(0,risk-8);atRisk=Math.max(0,atRisk-1);$("#riskScore").innerHTML=risk+"<em>/100</em>";$("#reportScore").innerHTML=risk+"<small>/100</small>";$("#riskBar").style.width=risk+"%";$("#atRisk").textContent=atRisk;$("#modal").classList.remove("show");page("training");toast("Training completed — risk reduced by 8 points")}
$("#modalTraining").onclick=train;$("#startTraining").onclick=()=>{toast("Training started...");setTimeout(train,700)};$("#devTraining").onclick=()=>toast("Developer course assigned");
